---

- name: Install the vhost redirect(s) for {{ static_site_site }}
  template: src=vhost_redirect.j2
            dest=/etc/nginx/sites-available/{{ static_site_site }}_redirect
            mode=0644
  notify:
    - restart nginx

- name: Enable the {{ static_site_shortname }} virtual host redirects
  file: path=/etc/nginx/sites-enabled/{{ static_site_site }}_redirect
        src=/etc/nginx/sites-available/{{ static_site_site }}_redirect
        state=link
  notify:
    - restart nginx

